"use client";
import { useEffect, useState } from "react";
import { signInWithEmailAndPassword, onAuthStateChanged } from "firebase/auth";
import { useRouter } from "next/navigation";
import { Loader2, LockKeyhole } from "lucide-react";
import { toast } from "sonner";
import { auth } from "@/lib/firebase";
import { Logo } from "@/components/ui";
export default function LoginPage() { const router = useRouter(); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [busy, setBusy] = useState(false); useEffect(() => onAuthStateChanged(auth, user => { if (user) router.replace("/admin"); }), [router]); async function login(e: React.FormEvent) { e.preventDefault(); setBusy(true); try { await signInWithEmailAndPassword(auth, email, password); router.replace("/admin"); } catch { toast.error("We couldn’t sign you in. Check your email and password."); } finally { setBusy(false); } } return <main className="grid min-h-screen place-items-center px-5"><div className="absolute inset-0 -z-10 bg-[radial-gradient(circle_at_top,rgba(109,93,252,.24),transparent_38%)]" /><div className="glass w-full max-w-md rounded-3xl p-7 shadow-2xl sm:p-9"><Logo /><div className="mt-10"><div className="grid h-11 w-11 place-items-center rounded-xl bg-brand-500/15 text-brand-400"><LockKeyhole className="h-5 w-5" /></div><h1 className="mt-5 text-2xl font-semibold">Welcome back</h1><p className="mt-2 text-sm text-slate-400">Sign in to manage your lead pipeline.</p></div><form onSubmit={login} className="mt-7 space-y-4"><label className="block text-sm font-medium">Email<input required type="email" value={email} onChange={e => setEmail(e.target.value)} placeholder="you@company.com" className="mt-1.5 w-full rounded-xl border border-white/10 bg-white/5 px-3 py-3 outline-none focus:border-brand-400" /></label><label className="block text-sm font-medium">Password<input required type="password" value={password} onChange={e => setPassword(e.target.value)} placeholder="••••••••" className="mt-1.5 w-full rounded-xl border border-white/10 bg-white/5 px-3 py-3 outline-none focus:border-brand-400" /></label><button disabled={busy} className="btn-primary mt-2 w-full disabled:opacity-70">{busy && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}{busy ? "Signing in…" : "Sign in securely"}</button></form></div></main>; }
